### ISSUE TITLE
Babies aren't evolvable

### ISSUE THREAD

**Issue by teamlowkey** [Blossomforth/BlossomsPokemonGoManager#567] opened 2017-02-27 22:33 UTC
Baby Pokemon (Magby, Elekid, etc.) show a **-** in the **CP Evolved** field. When you try to evolve them, it skips them with the message "Skipped evolving Elekid. Is already highest evolution."

**Comment by Wolfsblvt** [comment] 2017-02-28 14:40
Duplicate of #558.

**Closed as completed by Wolfsblvt** 2017-02-28 14:40 UTC
Labels: bug, duplicate
