### ISSUE TITLE
I can no longer log in from around 2017/03/08 AM 10:30(JST).

### ISSUE THREAD

**Issue by Sentaroh** [Blossomforth/BlossomsPokemonGoManager#576] opened 2017-03-08 02:37 UTC
[11:34:37]: Error: AsyncPokemonGoException
Unknown exception occurred. 
[11:34:38]: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
[11:34:38]: 	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:55)
[11:34:38]: 	at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:142)
[11:34:38]: 	at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:229)
[11:34:38]: 	at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:218)
[11:34:38]: 	at me.corriekay.pokegoutil.utils.helpers.LoginHelper.login(LoginHelper.java:66)
[11:34:38]: 	at me.corriekay.pokegoutil.data.managers.AccountController.logOn(AccountController.java:338)
[11:34:38]: 	at me.corriekay.pokegoutil.BlossomsPoGoManager.openOldGui(BlossomsPoGoManager.java:118)
[11:34:38]: 	at me.corriekay.pokegoutil.BlossomsPoGoManager.start(BlossomsPoGoManager.java:70)
[11:34:38]: 	at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:34)
[11:34:38]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Failed to send request: SESSION_INVALIDATED
[11:34:38]: 	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
[11:34:38]: 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
[11:34:38]: 	at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
[11:34:38]: 	at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:44)
[11:34:38]: 	... 8 more
[11:34:38]: Caused by: java.util.concurrent.ExecutionException: com.pokegoapi.exceptions.RemoteServerException: Failed to send request: SESSION_INVALIDATED
[11:34:38]: 	at com.pokegoapi.main.ServerRequestEnvelope$1.get(ServerRequestEnvelope.java:86)
[11:34:38]: 	at com.pokegoapi.main.ServerRequestEnvelope$1.get(ServerRequestEnvelope.java:70)
[11:34:38]: 	at com.pokegoapi.main.ServerRequestEnvelope$1.get(ServerRequestEnvelope.java:50)
[11:34:38]: 	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
[11:34:38]: 	at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
[11:34:38]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[11:34:38]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[11:34:38]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[11:34:38]: 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[11:34:38]: 	at rx.Observable.subscribe(Observable.java:9957)
[11:34:38]: 	at rx.Observable.subscribe(Observable.java:9924)
[11:34:38]: 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
[11:34:38]: 	... 10 more
[11:34:38]: Caused by: com.pokegoapi.exceptions.RemoteServerException: Failed to send request: SESSION_INVALIDATED
[11:34:38]: 	at com.pokegoapi.main.RequestHandler.sendInternal(RequestHandler.java:269)
[11:34:38]: 	at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:384)
[11:34:38]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Redarion** [comment] 2017-03-08 09:13
same problem here

**Comment by gsziklai** [comment] 2017-03-08 10:29
This might be related to the [ban warning](https://www.reddit.com/r/pokemongo/comments/5y6y6k/new_update_flags_your_account_if_you_use_iv/). I got one today. (PTC passwd login)

**Comment by kribjo** [comment] 2017-03-08 11:17
Same here - using Google Auth with OAuth Token. What login methods are you using?

**Comment by kribjo** [comment] 2017-03-08 11:18
Duplicate of https://github.com/Wolfsblvt/BlossomsPokemonGoManager/issues/575 .

**Comment by Sentaroh** [comment] 2017-03-08 15:19
I am using Google Auth with OAuth Token.

**Comment by schagnon** [comment] 2017-03-08 16:36
Sadly I'm 0-15 for that.


-Steven Chagnon
Lead Admin for
Tennis League Network, LLC:
Servicing 35 Tennis
Communities Nationwide.
It's not always about the ace.

**Comment by mcsmcs4321** [comment] 2017-03-08 17:03
Same problem here. Tried to login for 20 times but none success.

**Comment by r4dpere** [comment] 2017-03-08 17:17
Are some able to still use it or we are completely out?

**Comment by netgh0st** [comment] 2017-03-08 19:20
I believe there was a forced API update with 0.57.4 and all of the apps that are not using paid hashing service (Blossom, IvGo) stopped working.

**Comment by mlc130104** [comment] 2017-03-09 17:36
@netgh0st but i included a hash key in the config and still got no luck.

**Comment by notoriouspeb** [comment] 2017-03-10 19:17
I miss you, Blossom! Kicking myself for not copy/pasting my inventory... will be the first thing I do if you come back!

**Comment by Dog-Pack** [comment] 2017-03-11 12:40
Yep I not been able to log in for some time, with this or pokenurse.

**Comment by rafasemnick** [comment] 2017-03-12 02:06
Hey, @Wolfsblvt ! This tool don't work too, can you help us? This tool is fundamental to realize a good performance in the game.  Thanks.

**Comment by FernandoTBarros** [comment] 2017-03-12 03:17
Hi guys, this error is related to non-hahskey login.
Since 0.57.4 force update the 0.45 legacy login is turned off and SESSION_INVALIDATED is the error you got when try.
To continue using the BPGM tool (and all other tools around) you will need to get a hashkey now.

**Closed as completed by FernandoTBarros** 2017-03-12 03:17 UTC
Labels: question, wontfix / invalid

**Comment by rafasemnick** [comment] 2017-03-12 03:28
Você fala português?

Em 12 de mar de 2017 12:17 AM, "Fernando Teixeira Barros" <
notifications@github.com> escreveu:

**Comment by FernandoTBarros** [comment] 2017-03-12 03:40
Sim

**Comment by rafasemnick** [comment] 2017-03-12 03:43
Você é o criador dá planilha? Eu não falo inglês direito,fiquei meio
desesperado com ela parando de funcionar hahahaha há alguma solução?

Atenciosamente,

Rafael

Em 12 de mar de 2017 12:40 AM, "Fernando Teixeira Barros" <
notifications@github.com> escreveu:

**Comment by FernandoTBarros** [comment] 2017-03-12 04:57
No, I'm not the creator. There a lot of people involved since it's an open source tool.
To be able to login you will need to buy a hash key and configure it in config.json file.

----
Não, não sou o criador. Existem várias pessoas envolvidas uma vez que é uma ferramenta código aberto.
Para conseguir logar novamente vc vai precisar comprar uma hash key do pessoal da [Bossland ](talk.pogodev.org/d/54-getting-started-with-our-api-hashing-service) e configurar ela no arquivo config.json antes de abrir o BPGM.

**Comment by rafasemnick** [comment] 2017-03-12 05:13
hmm, é uma pena que não funcione mais gratuitamente....enfim, obrigado.

2017-03-12 1:57 GMT-03:00 Fernando Teixeira Barros <notifications@github.com
